schema_version = "1.0.0"
id = "gdcorner_rush_hour_vehicle_toolkit"
version = "1.6.3"
name = "Rush Hour Unreal Vehicle Toolkit"
tagline = "Prepare vehicles for Unreal Engine 5 and Rush Hour"
maintainer = "GDCorner <philip@gdcorner.com>"
type = "add-on"
blender_version_min = "4.2.0"
website = "https://www.gdcorner.com/products/RushHour.html"
copyright = ["2024-2026 GDCorner"]
license = [
  "SPDX:MIT",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".git",
  "*.zip",
  "test_scenes/",
  "TESTING.md",
  "test_runner.py",
]
